import type { ScaffoldRequest, ScaffoldTemplateId } from "./types";

export type ScaffoldFile = {
  path: string;
  contents: string;
};

function packageName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-|-$/g, "") || "mvp-project";
}

export function listTemplates(): { id: ScaffoldTemplateId; label: string; blurb: string }[] {
  return [
    {
      id: "web-saas",
      label: "Web SaaS slice",
      blurb: "Next.js app with a single authenticated-feeling core loop.",
    },
    {
      id: "landing-waitlist",
      label: "Landing + waitlist",
      blurb: "Brand-first landing page and email capture endpoint.",
    },
    {
      id: "api-service",
      label: "API service",
      blurb: "Minimal API with health check and one domain route.",
    },
    {
      id: "cli-tool",
      label: "CLI tool",
      blurb: "TypeScript CLI that runs one valuable command.",
    },
  ];
}

export function generateScaffold(req: ScaffoldRequest): ScaffoldFile[] {
  const name = packageName(req.name);
  const idea = req.idea.trim() || "Ship the smallest useful loop.";

  switch (req.template) {
    case "landing-waitlist":
      return landingFiles(name, idea);
    case "api-service":
      return apiFiles(name, idea);
    case "cli-tool":
      return cliFiles(name, idea);
    default:
      return webSaasFiles(name, idea);
  }
}

function webSaasFiles(name: string, idea: string): ScaffoldFile[] {
  return [
    {
      path: "package.json",
      contents: JSON.stringify(
        {
          name,
          version: "0.1.0",
          private: true,
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
          },
          dependencies: {
            next: "^15.0.0",
            react: "^19.0.0",
            "react-dom": "^19.0.0",
          },
          devDependencies: {
            typescript: "^5.0.0",
            "@types/node": "^20.0.0",
            "@types/react": "^19.0.0",
            "@types/react-dom": "^19.0.0",
          },
        },
        null,
        2,
      ),
    },
    {
      path: "README.md",
      contents: `# ${name}

MVP scaffold for: ${idea}

## Core loop
1. Open the app
2. Enter a goal
3. Get a next action

Generated by MVP Specialist.
`,
    },
    {
      path: "app/page.tsx",
      contents: `export default function Home() {
  return (
    <main style={{ fontFamily: "system-ui", maxWidth: 720, margin: "4rem auto", padding: 24 }}>
      <p style={{ letterSpacing: "0.08em", textTransform: "uppercase", fontSize: 12 }}>${name}</p>
      <h1>Do the one job that matters</h1>
      <p>${idea.replace(/`/g, "'")}</p>
      <form action="/api/run" method="post" style={{ display: "grid", gap: 12, marginTop: 24 }}>
        <label>
          Your goal
          <input name="goal" placeholder="What should we ship first?" style={{ display: "block", width: "100%", marginTop: 6, padding: 10 }} />
        </label>
        <button type="submit">Run core loop</button>
      </form>
    </main>
  );
}
`,
    },
    {
      path: "app/api/run/route.ts",
      contents: `import { NextResponse } from "next/server";

export async function POST(req: Request) {
  const form = await req.formData();
  const goal = String(form.get("goal") || "").trim();
  return NextResponse.json({
    ok: true,
    goal,
    nextAction: goal
      ? \`Write the smallest demo that proves: \${goal}\`
      : "Pick one user and one painful job, then ship only that.",
  });
}
`,
    },
  ];
}

function landingFiles(name: string, idea: string): ScaffoldFile[] {
  return [
    {
      path: "package.json",
      contents: JSON.stringify(
        {
          name,
          version: "0.1.0",
          private: true,
          scripts: { dev: "next dev", build: "next build", start: "next start" },
          dependencies: { next: "^15.0.0", react: "^19.0.0", "react-dom": "^19.0.0" },
          devDependencies: { typescript: "^5.0.0", "@types/react": "^19.0.0", "@types/node": "^20.0.0" },
        },
        null,
        2,
      ),
    },
    {
      path: "README.md",
      contents: `# ${name}

Landing + waitlist MVP for: ${idea}
`,
    },
    {
      path: "app/page.tsx",
      contents: `export default function Home() {
  return (
    <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 24, background: "linear-gradient(160deg,#dff3f0,#f7f1e8)" }}>
      <section style={{ maxWidth: 640, textAlign: "center" }}>
        <p style={{ fontSize: 14, letterSpacing: "0.14em", textTransform: "uppercase" }}>${name}</p>
        <h1 style={{ fontSize: "clamp(2.4rem,6vw,4rem)", lineHeight: 1.05 }}>Ship the waitlist, not the platform.</h1>
        <p style={{ fontSize: 18 }}>${idea.replace(/`/g, "'")}</p>
        <form action="/api/waitlist" method="post" style={{ display: "flex", gap: 8, justifyContent: "center", marginTop: 28 }}>
          <input name="email" type="email" required placeholder="you@company.com" style={{ padding: "12px 14px", minWidth: 240 }} />
          <button type="submit">Join waitlist</button>
        </form>
      </section>
    </main>
  );
}
`,
    },
    {
      path: "app/api/waitlist/route.ts",
      contents: `import { NextResponse } from "next/server";

export async function POST(req: Request) {
  const form = await req.formData();
  const email = String(form.get("email") || "").trim();
  // Replace with your store / email provider.
  console.log("waitlist:", email);
  return NextResponse.json({ ok: true, email });
}
`,
    },
  ];
}

function apiFiles(name: string, idea: string): ScaffoldFile[] {
  return [
    {
      path: "package.json",
      contents: JSON.stringify(
        {
          name,
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: {
            dev: "tsx watch src/server.ts",
            start: "tsx src/server.ts",
          },
          dependencies: {},
          devDependencies: { tsx: "^4.0.0", typescript: "^5.0.0", "@types/node": "^20.0.0" },
        },
        null,
        2,
      ),
    },
    {
      path: "README.md",
      contents: `# ${name}

API MVP for: ${idea}

Endpoints:
- GET /health
- POST /v1/run
`,
    },
    {
      path: "src/server.ts",
      contents: `import { createServer } from "node:http";

const port = Number(process.env.PORT || 8787);

const server = createServer(async (req, res) => {
  const url = new URL(req.url || "/", \`http://\${req.headers.host}\`);

  if (req.method === "GET" && url.pathname === "/health") {
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify({ ok: true, service: "${name}" }));
    return;
  }

  if (req.method === "POST" && url.pathname === "/v1/run") {
    const chunks: Buffer[] = [];
    for await (const chunk of req) chunks.push(chunk as Buffer);
    const body = Buffer.concat(chunks).toString("utf8");
    let input = body;
    try {
      input = JSON.parse(body).input ?? body;
    } catch {
      /* raw body */
    }
    res.writeHead(200, { "content-type": "application/json" });
    res.end(
      JSON.stringify({
        ok: true,
        idea: ${JSON.stringify(idea)},
        input,
        result: "Replace this with your domain logic.",
      }),
    );
    return;
  }

  res.writeHead(404, { "content-type": "application/json" });
  res.end(JSON.stringify({ error: "not_found" }));
});

server.listen(port, () => {
  console.log(\`${name} listening on http://localhost:\${port}\`);
});
`,
    },
  ];
}

function cliFiles(name: string, idea: string): ScaffoldFile[] {
  return [
    {
      path: "package.json",
      contents: JSON.stringify(
        {
          name,
          version: "0.1.0",
          type: "module",
          bin: { [name]: "./bin/run.mjs" },
          scripts: { start: "node ./bin/run.mjs" },
        },
        null,
        2,
      ),
    },
    {
      path: "README.md",
      contents: `# ${name}

CLI MVP for: ${idea}

\`\`\`bash
node bin/run.mjs "your input"
\`\`\`
`,
    },
    {
      path: "bin/run.mjs",
      contents: `#!/usr/bin/env node
const input = process.argv.slice(2).join(" ").trim();
const idea = ${JSON.stringify(idea)};

if (!input) {
  console.log(\`${name} — \${idea}\`);
  console.log("Usage: node bin/run.mjs <input>");
  process.exit(0);
}

console.log(JSON.stringify({
  tool: ${JSON.stringify(name)},
  input,
  next: \`Ship the smallest demo for: \${input}\`,
}, null, 2));
`,
    },
  ];
}
